name: Tests

on:
  push:
  pull_request:

jobs:
  test-api:
    name: API unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
        working-directory: cathouse-api
      - run: npm test
        working-directory: cathouse-api
      - run: npm run build
        working-directory: cathouse-api

  test-client:
    name: Client unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
        working-directory: cathouse-client
      - run: npm test
        working-directory: cathouse-client
      - run: npm run build
        working-directory: cathouse-client
